[jobs.run]
command = ["cargo", "watch", "-x", "run"]
need_stdout = true
background = false
watch = ["src", "Cargo.toml", "templates", "static", "migrations"]

# If you prefer the original behavior, you can run the `run.orig` job (build+run once).
[jobs.run.orig]
command = ["cargo", "run"]
need_stdout = true
background = false

